/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-10 02:27:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import pojo.Tour;
import pojo.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>旅游推荐首页</title>\r\n");
      out.write("    <link href=\"../css/item.food.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"../css/header.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"../css/footer.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"../css/slide.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 页面顶部-->\r\n");
      out.write("<header id=\"top\">\r\n");
      out.write("    <div id=\"logo\" class=\"lf\">\r\n");
      out.write("        <img src=\"../img/header/logo.png\" alt=\"logo\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"top_input\" class=\"lf\">\r\n");
      out.write("        <input id=\"input\" type=\"text\" placeholder=\"请输入您要搜索的内容\"/>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"../page/search.html?title=Java\" class=\"rt\"><img id=\"search\" src=\"../img/header/search.png\" alt=\"搜索\"/></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
User user = (User)request.getSession().getAttribute("user"); 
      out.write("\r\n");
      out.write("    <span>欢迎:[");
      out.print(user.getUname() );
      out.write("]登录</span>\r\n");
      out.write("    <div class=\"rt\">\r\n");
      out.write("        <ul class=\"lf\">\r\n");
      out.write("            <li><a href=\"AllTourServlet\" >首页</a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"../page/password-change.jsp\">设置</a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"MessageServlet\">留言版</a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"userLogOutServlet\">退出</a><b>|</b></li>\r\n");
      out.write("            <li><a href=\"../page/lookforward.jsp\">帮助</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- nav主导航-->\r\n");
      out.write("<div>&nbsp;</div>\r\n");
      out.write("<!-- banner部分-->\r\n");
      out.write("<div class=\"ck-slide\">\r\n");
      out.write("    <ul class=\"ck-slide-wrapper\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"DetailTourServlet?isbn=001\"><img src=\"../img/banner/banner1.png\" alt=\"\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li style=\"display:none\">\r\n");
      out.write("            <a href=\"DetailTourServlet?isbn=002\"><img src=\"../img/banner/banner2.png\" alt=\"\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li style=\"display:none\">\r\n");
      out.write("            <a href=\"DetailTourServlet?isbn=003\"><img src=\"../img/banner/banner3.png\" alt=\"\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li style=\"display:none\">\r\n");
      out.write("            <a href=\"DetailTourServlet?isbn=004\"><img src=\"../img/banner/banner4.png\" alt=\"\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li style=\"display:none\">\r\n");
      out.write("            <a href=\"DetailTourServlet?isbn=005\"><img src=\"../img/banner/banner5.png\" alt=\"\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("         <li style=\"display:none\">\r\n");
      out.write("            <a href=\"DetailTourServlet?isbn=006\"><img src=\"../img/banner/banner6.png\" alt=\"\"></a>\r\n");
      out.write("        </li> \r\n");
      out.write("    </ul>\r\n");
      out.write("    <a href=\"javascript:;\" class=\"ctrl-slide ck-prev\">上一张</a> \r\n");
      out.write("    <a href=\"javascript:;\" class=\"ctrl-slide ck-next\">下一张</a>\r\n");
      out.write("    <div class=\"ck-slidebox\">\r\n");
      out.write("        <div class=\"slideWrap\">\r\n");
      out.write("            <ul class=\"dot-wrap\">\r\n");
      out.write("                <li class=\"current\"><em>1</em></li>\r\n");
      out.write("                <li><em>2</em></li>\r\n");
      out.write("                <li><em>3</em></li>\r\n");
      out.write("                <li><em>4</em></li>\r\n");
      out.write("                <li><em>5</em></li>\r\n");
      out.write("                <li><em>6</em></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 特推部分-->\r\n");
      out.write("<!--商品-->\r\n");
      out.write("<div class=\"store\">\r\n");
      out.write("    <div class=\"store_top\">\r\n");
      out.write("        <img src=\"../img/banner/icon.png\" alt=\"\"/>\r\n");
      out.write("        热搜排行\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

    ArrayList<Tour> tours = (ArrayList<Tour>)request.getAttribute("tours");
    /* System.out.println(tours.size()); */
    for(int i=0;i<tours.size();i++){
    	Tour tour = tours.get(i);
      if (i % 4 == 0) {
    
      out.write("\r\n");
      out.write("    \t<div class=\"store_content\">\r\n");
      out.write("      ");

      }
      
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("  <a href=\"DetailTourServlet?isbn=");
      out.print(tour.getIsbn());
      out.write("\">\r\n");
      out.write("  <img src=\"../img/goods/");
      out.print(tour.getIsbn() );
      out.write("/index.jpg\" alt=\"\"/></a>\r\n");
      out.write("  <p class=\"one\">");
      out.print(tour.getTitle() );
      out.write("</p>\r\n");
      out.write("  <p class=\"three\">\r\n");
      out.write("    <span>\r\n");
      out.write("    位置：<span>");
      out.print(tour.getLocation() );
      out.write("</span>\r\n");
      out.write("    </span>\r\n");
      out.write("  </p>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t");

		if (i % 4 == 3) {
		
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
	
		}
		
      out.write("\t\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"foot_box\">\r\n");
      out.write("    <div class=\"icon1 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon1.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon2 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon2.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon3 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon3.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon4 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon4.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"../js/index.js\"></script>\r\n");
      out.write("<script src=\"../js/slide.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $('.ck-slide').ckSlide({\r\n");
      out.write("        autoPlay: true,//默认为不自动播放，需要时请以此设置\r\n");
      out.write("        dir: 'x',//默认效果淡隐淡出，x为水平移动，y 为垂直滚动\r\n");
      out.write("        interval:3000//默认间隔2000毫秒\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
