/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-10 02:25:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>寸金出行通旅游推荐登陆页面</title>\r\n");
      out.write("<link href=\"../css/header.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../css/footer.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../css/animate.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"../css/login.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 页面顶部-->\r\n");
      out.write("\t<header id=\"top\">\r\n");
      out.write("\t\t<div class=\"top\">\r\n");
      out.write("\t\t\t<img src=\"../img/header/logo.png\" alt=\"\" /> <span> 欢迎登录旅游推荐网页</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div id=\"cover\" class=\"rt\">\r\n");
      out.write("\t\t\t<form id=\"fm-login\" name=\"form1\" method=\"post\"\r\n");
      out.write("\t\t\t\taction=\"userLoginServlet\">\r\n");
      out.write("\t\t\t\t<div class=\"txt\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t旅游推荐 <span> <a href=\"regist.jsp\">新用户注册</a> </span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"请输入您的用户名\" name=\"uname\" id=\"uname\"\r\n");
      out.write("\t\t\t\t\t\t\trequired> <span></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"upwd\" placeholder=\"请输入您的密码\" name=\"upwd\"\r\n");
      out.write("\t\t\t\t\t\t\trequired minlength=\"6\" maxlength=\"15\"> <span></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chose\"></div>\r\n");
      out.write("\t\t\t\t\t<input class=\"button_login\" type=\"submit\" value=\"登录\" id=\"bt-login\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<div id=\"foot_box\">\r\n");
      out.write("    <div class=\"icon1 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon1.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon2 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon2.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon3 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon3.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"icon4 lf\">\r\n");
      out.write("        <img src=\"../img/footer/icon4.png\" alt=\"\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<!--错误提示-->\r\n");
      out.write("\t<div id=\"showResult\"></div>\r\n");
      out.write("\t<script src=\"../js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("    $(\"#uname\").blur(function(){\r\n");
      out.write("        var data = $(\"#uname\").val();\r\n");
      out.write("        if (data == null || data == \"\") {\r\n");
      out.write("            $(\"#showResult\").text(\"用户名不能为空！\");\r\n");
      out.write("            $(\"#showResult\").css(\"color\",\"red\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type:\"POST\",\r\n");
      out.write("            url:\"/tour/user/page/userUnameCheckServlet\",\r\n");
      out.write("            data:\"uname=\"+data,\r\n");
      out.write("            beforeSend:function(XMLHttpRequest)\r\n");
      out.write("            {\r\n");
      out.write("                $(\"#showResult\").text(\"正在查询\");\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            success:function(msg)\r\n");
      out.write("            {\r\n");
      out.write("                if(msg ===\"yes\"){\r\n");
      out.write("                    $(\"#showResult\").text(\"\");\r\n");
      out.write("                }else if(msg === 'no'){\r\n");
      out.write("                    $(\"#showResult\").text(\"该用户不存在\");\r\n");
      out.write("                    $(\"#showResult\").css(\"color\",\"red\");\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error:function()\r\n");
      out.write("            {\r\n");
      out.write("                //错误处理\r\n");
      out.write("            \t$(\"#showResult\").text(\"系统异常！\");\r\n");
      out.write("                $(\"#showResult\").css(\"color\",\"red\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    $('#bt-login').click(function(){\r\n");
      out.write("        window.location.href =  \"index.html\";\r\n");
      out.write("        //读取用户的输入——表单序列化\r\n");
      out.write("        var inputData = $('#fm-login').serialize();\r\n");
      out.write("        // alert(inputData);\r\n");
      out.write("        //异步提交请求，进行验证\r\n");
      out.write("        $.ajax({\r\n");
      out.write("        \tasync: true,\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            url: 'login.action',\r\n");
      out.write("            data: inputData,\r\n");
      out.write("            success: function(txt, msg, xhr){\r\n");
      out.write("            \t// alert(\"*\"+txt+\"*\");\r\n");
      out.write("                if(txt=='yes'){  //登录成功\r\n");
      out.write("                    var loginName = $('[name=\"uname\"]').val();\r\n");
      out.write("                    console.log(loginName);\r\n");
      out.write("                    window.location.href =  \"index.html\";\r\n");
      out.write("                }else{ //登录失败\r\n");
      out.write("                    $('#showResult').html('登录失败！');\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }); \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
